### ISSUE TITLE
checksum error with accessor v0.16~preview.128.20+135

### ISSUE THREAD

**Issue by mbarbin** [janestreet/opam-repository#25]
I'm experimenting with a new workflow locally using opam monorepo and pulling from jane-bleeding, and I'm hitting the following error message during a `opam monorepo pull`:

```
opam-monorepo: [ERROR] Failed to pull https://github.com/janestreet/accessor/archive/677e016df61732f358eba3904747b275938d8f46.tar.gz
(Bad checksum, expected sha256=e9245e17d15ef95f3d5b36241e4bbce60e05e57381b8546e26544641a91e051b)
```

I don't have experience yet using opam and this janestreet repo that way, so I currently don't understand the issue. Note that several jane-bleeding packages of this version seem to update just fine, so I don't know why accessor would be special.

Do you know how checksum are computed locally by opam for verification, and how I could trouble shoot ?

Thanks!

**Comment by Enoumy** [comment]
Hmm, not a solution to the failing checksums, but I also came across this issue when running `opam install bonsai` on the failing preview.

I got around this by sending in `--no-checksums` to `opam install`. I am unsure if `opam monorepo pull` has a similar argument

**Comment by dkalinichenko-js** [comment]
We are investigating the problem, seems like something broke in our export pipeline. The latest push also has broken checksums.

**Comment by dkalinichenko-js** [comment]
For now, please use `--no-checksums` in `opam install`. The actual contents of tarballs are unaffected.

**Comment by dkalinichenko-js** [comment]
The issue has been fixed, thanks for the report! Please run `opam update` to ensure you have the newest commit.
