### ISSUE TITLE
migrate-parsetree still bugged out of the box

### ISSUE THREAD

**Issue by vbmithr** [janestreet/opam-repository#4]

**Comment by vbmithr** [comment]
Some additional info: In order to use `ppx_deriving` with janestreet plugins, I need `ppx_ast` to be able to correctly dynlink `ocaml_migrate_parsetree`. I have provided a patch for ocaml_migrate_parsetree so that the cmxs file is indeed built and installed.

Could you make sure that an installation of ppx_ast triggers a correct installation of ocaml_migrate_parsetree with `migrate_parsetree.cmxs` correctly built and installed?
Thanks.

**Comment by trefis** [comment]
We removed migrate-parsetree from our repo and are now using the upstream opam one.
Thank you for your patience.
